Repository nadchif/adobe-brackets-encode-decode, pull requests merged in 2020-05, with the labels that each got.

#35 updated context menu : README
  README.md
  screenshots/context-menu-updated-dark.png
Labels: documentation

#33 More unit tests
  package-lock.json
  package.json
  spec/MD5.spec.js
  spec/PHPSerialize.spec.js
  spec/SHA256.spec.js
  spec/hexadecimal.spec.js
  spec/htmlentities.spec.js
  spec/morsecode.spec.js
  spec/nl2br.spec.js
  spec/support/mock.brackets.js
Labels: Testing

#39 Adding encoding/decoding for ASCII
  README.md
  package-lock.json
  spec/PHPSerialize.spec.js
  spec/SHA256.spec.js
  spec/SHA512.spec.js
  spec/ascii.spec.js
  src/convertors/ascii.js
  src/main.js
Labels: enhancement
